# Generated by Django 5.0 on 2024-01-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='message',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
