# Generated by Django 5.0 on 2024-01-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_userinfo_message'),
    ]

    operations = [
    ]
